desc "Match lane"
lane :apps_match do
    ENV["MATCH_FORCE_ENTERPRISE"] = "1"
    match(
        git_url: "https://github.com/iut-lyon1-2016/certificates.git",
        type: "development",
        app_identifier: "fr.appsolute.IUTDemo20161",
        username: "iut-2016@appsolute.fr",
        readonly: true
    )
     match(
        git_url: "https://github.com/iut-lyon1-2016/certificates.git",
        type: "enterprise",
        app_identifier: "fr.appsolute.IUTDemo20161",
        username: "iut-2016@appsolute.fr",
        readonly: true
    )
        
    end

   desc "Distribute a new app"
		lane :apps_build do 
    
		changelog = prompt(text: "Enter the change log: ", multi_line_end_keyword: "END")

			git_pull()	

  	buildNumber= increment_build_number()
  	
  	git_add(path:".")
  	git_commit(path:".", message:buildNumber)
  	push_to_git_remote(tags:"onetag")



    		gym(
    			workspace: "Coderproprement.xcworkspace",
    			scheme: "CoderProprement",
    			clean: true,
    			configuration: "Release",
        		use_legacy_build_api: true
    		)

    	crashlytics(
        	api_token: "fc9d87b2efd9490e1a216989a7ebb86e7d59dfed",
        	build_secret: "34fe58a4e2ba0b70c2542972f64f088e9b50c159f18624ff3bd2ac2f453874f4",
       	 	emails: ["william@appsolute.fr"]
  )


  


#  	slack(
 # 	message:changelog,
  #	channel:"fastlane-messages",
 # 	slack_url: "https://hooks.slack.com/services/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",
#  	username:"jonas_paul"
 # 	)



end 